/* Automatically generated by po2tbl.sed from soundmodem.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Mode", 2},
  {"IO", 3},
  {"Channel Access", 4},
  {"Modulator", 5},
  {"Demodulator", 6},
  {"Packet IO", 7},
  {"SoundModem Configurator", 8},
  {"File", 9},
  {"New", 10},
  {"Configuration", 11},
  {"Channel", 12},
  {"Delete", 13},
  {"Quit", 14},
  {"Diagnostics", 15},
  {"Scope", 16},
  {"Spectrum", 17},
  {"Modem", 18},
  {"AO-40 P3D Modem", 19},
  {"Help", 20},
  {"About", 21},
  {"Select File", 22},
  {"About SoundModem Configurator", 23},
  {"Copyright 2000", 24},
  {"Thomas Sailer", 25},
  {"Ok", 26},
  {"New Configuration", 27},
  {"Configuration Name", 28},
  {"Cancel", 29},
  {"OK", 30},
  {"Error", 31},
  {"Spectrum Display", 32},
  {"Pointer", 33},
  {"PTT", 34},
  {"DCD", 35},
  {"Freeze when not DCD", 36},
  {"Receive Packets/Bits", 37},
  {"Clear Count", 38},
  {"Zeros", 39},
  {"Ones", 40},
  {"Total", 41},
  {"Received Packets", 42},
  {"Received Bits", 43},
  {"AO-40 Phase 3D Receive Window", 44},
  {"Receiver Status", 45},
  {"Carrier Frequency", 46},
  {"Hz", 47},
  {"Decode All Packets (Faulty CRC)", 48},
  {"Received Decoded Packets", 49},
  {"Received Raw Packets", 50},
  {"Couldn't find pixmap file: %s", 51},
  {"Error loading pixmap file: %s", 52},
};

int _msg_tbl_length = 52;
